const sampleDocuments = [
    {
        title: "Permanent Residential Certificate (PRC) in Rural Areas",
        description:
            "Application process for obtaining a PRC for tribal and non-tribal citizens in rural areas.",
        downloadLink:
            "https://drive.google.com/file/d/1b9UxqPQtAUF-JeWnrxZg6KENmLf-6Khb/view",
        applyLink:
            "https://sewasetu.assam.gov.in/site/service-apply/permanent-residential-certificate-prc-in-rural-areas-nchac",
        state: "Arunachal Pradesh",
        department: "Revenue & Disaster Management",
        guidelines: [
            "Register on the portal before applying.",
            "Login and select the service you want to apply for.",
            "Fill up the form and upload required documents.",
            "After submission, track your application using the reference number.",
            "If any rectification is required, a query is sent via SMS & Email.",
            "A physical inspection may be scheduled for verification.",
            "After successful verification, visit the NCHAC office to pay the fee.",
            "Download the PRC from the ARTPS Portal after payment.",
        ],
        requiredDocuments: [
            "Land Khajna up-to-date receipt (Mandatory)",
            "PRC of parent’s if exists, else No Objection Certificate from Gaon Burha (Mandatory)",
            "Certified copy of council’s electoral roll (Mandatory)",
            "Birth certificate (for minors) (Mandatory)",
            "Recent passport size photo (Mandatory)",
        ],
    },
    {
        title: "Income Certificate",
        description:
            "Application process for obtaining an income certificate for various purposes.",
        downloadLink:
            "https://sivasagar.assam.gov.in/sites/default/files/public_utility/INCOME.pdf",
        applyLink:
            "http://sewasetu.assam.gov.in/site/service-apply/application-for-income-certificate",
        state: "Assam",
        department: "Revenue & Disaster Management",
        guidelines: [
            "Register on the portal before applying.",
            "Login and select the service you want to apply for.",
            "Fill up the form and upload required documents.",
            "After submission, track your application using the reference number.",
            "After successful verification, download the certificate from the ARTPS portal.",
        ],
        requiredDocuments: [
            "Address Proof (Mandatory)",
            "Identity Proof (Mandatory)",
            "Land Revenue Receipt (Mandatory)",
            "Salary Slip (Optional)",
            "Any other supporting document (Optional)",
        ],
    },
    {
        title: "Caste Certificate",
        description: "Get your SC/ST/OBC caste certificate for reservation and other purposes.",
        downloadLink: "https://example.com/caste-certificate-guidelines.pdf",
        applyLink: "https://edistrict.up.gov.in/",
        state: "Uttar Pradesh",
        department: "Social Welfare Department",
        guidelines: [
            "Login with your credentials.",
            "Fill the caste certificate application form.",
            "Upload necessary documents.",
            "Submit and track the status online.",
            "Collect the certificate from Tehsil or download from the portal.",
        ],
        requiredDocuments: [
            "Application Form (Mandatory)",
            "Affidavit (Mandatory)",
            "Address Proof (Mandatory)",
            "Proof of Caste (Mandatory)",
            "Passport-size Photo (Mandatory)",
        ],
    },
    {
        title: "Domicile Certificate",
        description: "Apply for domicile certificate for state residency proof.",
        downloadLink: "https://example.com/domicile-format.pdf",
        applyLink: "https://aaplesarkar.mahaonline.gov.in/",
        state: "Maharashtra",
        department: "Revenue Department",
        guidelines: [
            "Register on Aaple Sarkar portal.",
            "Select Domicile Certificate from the service list.",
            "Upload scanned documents and photo.",
            "Pay application fee online.",
            "Certificate will be issued after verification.",
        ],
        requiredDocuments: [
            "Ration Card (Mandatory)",
            "School Leaving Certificate (Mandatory)",
            "Address Proof (Mandatory)",
            "Birth Certificate (Mandatory)",
        ],
    },
    {
        title: "Senior Citizen Certificate",
        description: "For availing various benefits and schemes for senior citizens.",
        downloadLink: "https://example.com/senior-citizen-info.pdf",
        applyLink: "https://edistrict.delhigovt.nic.in/",
        state: "Delhi",
        department: "Department of Social Welfare",
        guidelines: [
            "Register on e-District Delhi portal.",
            "Fill application form for senior citizen ID.",
            "Upload photograph and age proof.",
            "Submit and track application status.",
            "Download or collect the certificate.",
        ],
        requiredDocuments: [
            "Age Proof (Mandatory)",
            "Address Proof (Mandatory)",
            "Aadhaar Card (Mandatory)",
            "Passport-size Photo (Mandatory)",
        ],
    },
    {
        title: "Birth Certificate",
        description: "Apply for official birth certificate from Municipal records.",
        downloadLink: "https://example.com/birth-certificate-process.pdf",
        applyLink: "https://www.wb.gov.in/",
        state: "West Bengal",
        department: "Municipal Affairs Department",
        guidelines: [
            "Visit the local municipal office or apply online.",
            "Provide birth details and hospital information.",
            "Attach parents' identity documents.",
            "Track status using application number.",
            "Collect the certificate or download PDF.",
        ],
        requiredDocuments: [
            "Hospital Discharge Summary (Mandatory)",
            "Parents’ ID Proof (Mandatory)",
            "Address Proof (Mandatory)",
        ],
    },
    {
        title: "Death Certificate",
        description: "Apply for death certificate for legal and official purposes.",
        downloadLink: "https://example.com/death-certificate-guidelines.pdf",
        applyLink: "https://kerala.gov.in/",
        state: "Kerala",
        department: "Local Self Government Department",
        guidelines: [
            "Submit application online or at the local panchayat/municipality.",
            "Provide details like name, date, and place of death.",
            "Attach necessary documents.",
            "Track application online.",
            "Download the certificate after approval.",
        ],
        requiredDocuments: [
            "Medical Certificate of Death (Mandatory)",
            "ID Proof of Applicant (Mandatory)",
            "Address Proof (Mandatory)",
        ],
    },
    {
        title: "Ration Card Application",
        description: "Apply for new ration card for accessing subsidized food grains.",
        downloadLink: "https://example.com/ration-card-format.pdf",
        applyLink: "https://tnesevai.tn.gov.in/",
        state: "Tamil Nadu",
        department: "Civil Supplies and Consumer Protection Department",
        guidelines: [
            "Create account on TNeGA portal.",
            "Select ‘Ration Card Services’.",
            "Fill in family details and upload documents.",
            "Pay applicable processing fee.",
            "Track application and receive card by post or download.",
        ],
        requiredDocuments: [
            "Aadhaar Card of all family members (Mandatory)",
            "Address Proof (Mandatory)",
            "Electricity Bill (Optional)",
        ],
    },
    {
        title: "Marriage Certificate",
        description: "Legal certificate of marriage for official documentation.",
        downloadLink: "https://example.com/marriage-guidelines.pdf",
        applyLink: "https://biharregd.gov.in/",
        state: "Bihar",
        department: "Registration Department",
        guidelines: [
            "Visit Bihar Registration portal.",
            "Fill details of bride and groom.",
            "Upload age proof and marriage invitation.",
            "Schedule date for verification.",
            "Download certificate after approval.",
        ],
        requiredDocuments: [
            "Identity Proof of both spouses (Mandatory)",
            "Marriage Invitation Card (Optional)",
            "Age Proof (Mandatory)",
            "Passport-size Photos (Mandatory)",
        ],
    },
    {
        title: "Disability Certificate",
        description: "For obtaining disability benefits and government support.",
        downloadLink: "https://example.com/disability-cert.pdf",
        applyLink: "https://edistrict.cgstate.gov.in/",
        state: "Chhattisgarh",
        department: "Social Justice & Empowerment",
        guidelines: [
            "Visit eDistrict Chhattisgarh.",
            "Fill application with medical history.",
            "Upload scanned reports and doctor reference.",
            "Submit and track via portal.",
            "Certificate issued after medical board review.",
        ],
        requiredDocuments: [
            "Medical Reports (Mandatory)",
            "Photo ID (Mandatory)",
            "Residence Proof (Mandatory)",
        ],
    },
    {
        title: "Character Certificate",
        description: "Used for job applications, higher studies, or visa.",
        downloadLink: "https://example.com/character-format.pdf",
        applyLink: "https://rajasthan.gov.in/",
        state: "Rajasthan",
        department: "Home Department",
        guidelines: [
            "Apply online through SSO Rajasthan portal.",
            "Fill personal and background details.",
            "Police verification may be initiated.",
            "Track status online.",
            "Download certificate after approval.",
        ],
        requiredDocuments: [
            "ID Proof (Mandatory)",
            "Address Proof (Mandatory)",
            "Photograph (Mandatory)",
        ],
    },
];

module.exports = { data: sampleDocuments };
